POST http://localhost:3003/api/login
content-type: application/json

{
  "username": "elias.vakkuri",
  "password": ""
}

### Fail scenario: invalid password

POST http://localhost:3003/api/login
content-type: application/json

{
  "username": "elias.vakkuri",
  "password": "väärä"
}
